# Generated by Django 5.2.5 on 2025-09-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
    ]
